config/routes.rb
Learning::Application.routes.draw do
  get "activities/index"
  resources :users do
    member do
      get :following, :followers
    end
    resources :likes, only: [:create, :destroy, :index]
    resources :dislikes, only: [:create, :destroy, :index]
    resources :bookmarks, only: [:create, :destroy, :index]
  end

  resources :resources
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/about', to: 'static_pages#about', via: 'get'

  get 'resources/languages/:language', to: 'resources#index', as: :language 
  get 'resources/kinds/:kind', to: 'resources#index', as: :kind
  get 'resources/levels/:level', to: 'resources#index', as: :level 
  get 'resources/prices/:price', to: 'resources#index', as: :price        

  

end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert text-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>				

app/views/shared/_recommendations.html.erb
<% @user ||= current_user %>
<div class="stats">
	<strong>Recommendations:</strong> 	
	<a href="<%= user_likes_path(@user) %>">
		<strong id="likes" class="stat">
			<%= @user.likes.count %>
		</strong>
		likes
	</a>
	|
	<a href="<%= user_dislikes_path(@user) %>">
		<strong id="dislikes" class="stat">
			<%= @user.dislikes.count %>
		</strong>
		dislikes
	</a>
	|
	<a href="<%= user_bookmarks_path(@user) %>">
		<strong id="bookmarks" class="stat">
			<%= @user.bookmarks.count %>
		</strong>
		bookmarks
	</a>	
</div>					

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<strong>Connections:</strong> 
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		following
	</a>
	|
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>	