config/routes.rb
Learning::Application.routes.draw do
  get "activities/index"
  resources :users do
    member do
      get :following, :followers
    end
    resources :likes, only: [:create, :destroy, :index]
    resources :dislikes, only: [:create, :destroy, :index]
    resources :bookmarks, only: [:create, :destroy, :index]
  end

  resources :resources
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/about', to: 'static_pages#about', via: 'get'

  get 'resources/languages/:language', to: 'resources#index', as: :language 
  get 'resources/kinds/:kind', to: 'resources#index', as: :kind
  get 'resources/levels/:level', to: 'resources#index', as: :level 
  get 'resources/prices/:price', to: 'resources#index', as: :price        

  

end

app/views/resources/_bookmark.html.erb
<%= form_tag(user_bookmarks_path(current_user)) do %>
  <%= hidden_field_tag "resource_id", @resource.id %>
  <%= submit_tag "Bookmark", class: "btn btn-primary" %>
<% end %>

app/views/resources/_dislike.html.erb
<%= form_tag(user_dislikes_path(current_user)) do %>
  <%= hidden_field_tag "id", @resource.id %>
  <%= submit_tag "Dislike", class: "btn btn-primary" %>
<% end %>

app/views/resources/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div class="alert alert-warning">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>
      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field"> 
    <%= f.label :kind_list, "Type" %><br>
    <%= f.text_field :kind_list %>
  </div>
  <div class="field">
    <%= f.label :level_list, "Level" %><br>
    <%= f.text_field :level_list %>
  </div>
  <div class="field">
    <%= f.label :price_list, "Cost" %><br>
    <%= f.text_field :price_list %>
  </div>
  <div class="field">
    <%= f.label :language_list, "Language/Framework" %><br>    
    <%= f.text_field :language_list %> 
  </div>
  <div class="actions">
      <%= f.submit "Submit", class: "btn btn-large btn-primary" %>    
  </div>
<% end %>
  </div>  
</div>

app/views/resources/_like.html.erb
<%= form_tag(user_likes_path(current_user)) do %>
  <%= hidden_field_tag "id", @resource.id %>
  <%= submit_tag "Like", class: "btn btn-primary" %>
<% end %>

app/views/resources/_likes_button.html.erb
<div class="row">
	<div class="col-md-6">
		<%= render (current_user.likes?(@resource) ? 'unlike' : 'like') %>
	</div>
	<div class="col-md-6">	
		<%= render (current_user.dislikes?(@resource) ? 'undislike' : 'dislike') %>
	</div>	
</div>

app/views/resources/_resource.html.erb
	<li>
		<%= link_to resource.name, resource %>
	</li>

app/views/resources/_undislike.html.erb
<%= form_tag(user_dislike_path(current_user, @resource.id), method: :delete) do %>
  <%= submit_tag "Undislike", class: "btn btn-primary" %>
<% end %>

app/views/resources/_unlike.html.erb
<%= form_tag(user_like_path(current_user, @resource.id), method: :delete) do %>
  <%= submit_tag "Unlike", class: "btn btn-primary" %>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<% provide(:title, 'Resources') %>

<h1>Resources</h1>

<table>
  <thead>
    <tr>
      <th class="col-md-8"></th>
      <th class="col-md-1">Type</th>
      <th class="col-md-1">Level</th>
      <th class="col-md-1">Cost</th>
      <th class="col-md-1">Language/Framework</th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td class="col-md-8"><h3><%= link_to resource.name, resource %></h3>
        <p><%= resource.description %>
        <%= link_to 'Edit', edit_resource_path(resource) %> | 
        <%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></p></td>
        <td class="col-md-1"><%= raw resource.kind_list.map{ |k| link_to k, kind_path(k) }.join(' ') %></td>
        <td class="col-md-1"><%= raw resource.level_list.map{ |l| link_to l, level_path(l) }.join(' ') %></td>
        <td class="col-md-1"><%= raw resource.price_list.map{ |p| link_to p, price_path(p) }.join(' ') %></td>
        <td class="col-md-1"><%= raw resource.language_list.map{ |l| link_to l, language_path(l) }.join(' ') %></td>
      </tr>
    <% end %>
  </tbody>
  </div>
</table>

<br>

<button type="button" class="btn btn-default"><%= link_to 'Add a new resource', new_resource_path %></button>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<% provide(:title, @resource.name) %>
  <h2><%= @resource.name %></h2>
  <div class="col-md-4">  
    <div class= "row">
      <div class="col-md-8">
        <%= @resource.liked_by_count %> Likes
      </div>
      <div class="col-md-8">
        <%= @resource.disliked_by_count %> Dislikes
      </div>   
    </div>
    <%= render 'likes_button' if signed_in? %>
<div class="well">
<p>
  <strong>Url:</strong>
  <%= link_to @resource.url, @resource.url %>
</p>

<p>
  <strong>Language/Framework:</strong>
    <ul>
    <% @resource.language_list.each do |l| %>
      <li><%= link_to l, kind_path(l) %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Kind:</strong>
  <ul>
    <% @resource.kind_list.each do |k| %>
      <li><%= link_to k, kind_path(k) %></li>
    <% end %>
  </ul>
  </p>

<p>
  <strong>Level:</strong>
    <ul>
    <% @resource.level_list.each do |l| %>
      <li><%= link_to l, kind_path(l) %></li>
    <% end %>
  </ul>
  </p>

<p>
  <strong>Price:</strong>
    <ul>
    <% @resource.price_list.each do |p| %>
      <li><%= link_to p, kind_path(p) %></li>
    <% end %>
  </ul>
  </p>
</div>

<%= link_to 'Edit', edit_resource_path(@resource), class: "btn btn-default" %> 
<%= link_to 'Back', resources_path, class: "btn btn-default" %>
</div>

<div class="col-md-8">
<p>
  <strong>Description:</strong>
  <%= @resource.description %>
</p>
</div>

app/views/resources/unbookmark.html.erb
<%= form_tag(user_bookmark_path(current_user, @bookmark), method: :delete) do %>
  <%= submit_tag "Unbookmark", class: "btn btn-primary" %>
<% end %>