config/routes.rb
Learning::Application.routes.draw do
  get "activities/index"
  resources :users do
    member do
      get :following, :followers
    end
    resources :likes, only: [:create, :destroy, :index]
    resources :dislikes, only: [:create, :destroy, :index]
    resources :bookmarks, only: [:create, :destroy, :index]
  end

  resources :resources
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/about', to: 'static_pages#about', via: 'get'

  get 'resources/languages/:language', to: 'resources#index', as: :language 
  get 'resources/kinds/:kind', to: 'resources#index', as: :kind
  get 'resources/levels/:level', to: 'resources#index', as: :level 
  get 'resources/prices/:price', to: 'resources#index', as: :price        

  

end

app/views/layouts/_footer.html.erb
<div id="footer">
	<div class="container">
	<center>
		<p>Collect<span><</span>div<span>></span> &copy; <%= Time.now.year %><p>
	</center>
</div>
</div>	

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#global-nav">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <span class ="navbar-brand"><%= link_to root_path do %>
      <%= image_tag "collectdiv.png", :class => "img-responsive" %>
      <% end %>
  </div>
        
        <div class="collapse navbar-collapse" id="global-nav">        
                <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Resources", resources_path %></li>
          <li><%= link_to "About", about_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
        </div>        
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", media: "all", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="wrap">
	<%= render 'layouts/header' %>	

	<div class="container">
		<% flash.each do |key, value| %>
			<div class="alert text-<%= key %>"><%= value %></div>
		<% end %>	
		<%= yield %>
			</div>
	</div>			
		<%= render 'layouts/footer' %>	
</body>
</html>